# Generated by Django 3.1.2 on 2020-10-09 07:23

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
